version: 2
jobs:
  build:
    docker:
        - image: kaikuehne/pyenv:latest

    working_directory: /tmp/app

    steps:
        - checkout
        - setup_remote_docker

        - restore_cache:
            keys:
                - v1-project-{{ arch }}-{{ checksum "tox.ini" }}
                - v1-project-
        - run:
            command: |
                pyenv --version
                pyenv install --list
                pyenv install --keep --skip-existing 2.7.14
                pyenv install --keep --skip-existing 3.4.7
                pyenv install --keep --skip-existing 3.5.4
                pyenv install --keep --skip-existing 3.6.4
                pyenv rehash
                pyenv versions
                pyenv local  2.7.14 3.6.4 3.5.4 3.4.7
                pip install --upgrade pip
                pip install tox tox-pyenv
                tox
            environment:
              PATH: "/root/pyenv/bin:/root/pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
              PYENV_ROOT: "/root/pyenv"
            shell: /bin/bash

        - save_cache:
              key: v1-project-{{ arch }}-{{ checksum "tox.ini" }}
              paths:
                  - /root/pyenv
