version: 2
shared: &shared
    working_directory: ~/circleci-python-percy-client
    steps:
      - checkout  # checkout source code to working directory
      - run:
            command: |  # use pipenv to install dependencies
                pip install -r requirements_dev.txt
      - run:
          name: Run tests
          command: py.test
jobs:
  python-27:
      <<: *shared
      docker:
          - image: circleci/python:2.7

workflows:
  version: 2
  build:
    jobs:
      - "python-27"
