version: 2
jobs:
  build:
    working_directory: ~/circleci-tox
    docker:
      - image: circleci/python:3.5.7 # every job must define an image for the docker executor and subsequent jobs may define a different image.
    steps:
        - checkout  # checkout source code to working directory
        - run:
              command: |  # use pipenv to install dependencies
                  sudo pip install -U tox
        - run:
              command: tox
